img_filter_condition = {
    'image1': '',
    'image2': '',
    'image3': '',
    'image4': '',
    'image5': '',
    'image6': '',
    'image7': '',
    'image8': '',
    'image9': '',
    'image10': '',
    'image11': '',
    'image12': '',
    'image13': '',
    'image14': '',
    'image15': '',
    'image16': '',
    'image17': '',
    'image18': '',
    'image19': '',
    'image20': '',
}