# Generated by Django 4.2.1 on 2023-05-22 20:19

from django.db import migrations, models
import django.db.models.deletion
import ghar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('bhk', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(default=0)),
                ('ownership', models.CharField(max_length=255)),
                ('boundary', models.IntegerField(default=0)),
                ('gated', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=0)),
                ('how_soon', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_count', models.IntegerField(default=1)),
                ('floor', models.IntegerField(default=0)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghar.agent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ghar.models.property_image_path)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghar.property')),
            ],
        ),
    ]
